version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - run:
          name: test
          command: bundle exec rspec
      - ruby/bundle-install
