version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle exec rspec --profile --order=random
      - store_artifacts:
          path: ~/simplecov
      - store_test_results:
          path: ~/simplecov
      - ruby/bundle-install
