version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    working_directory: ~/upload_app
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: bundle check || bundle install
      - run: yarn install --check-files
      - run: rails db:migrate RAILS_ENV=development
      - run:
          name: test
          command: bundle exec rspec
      - ruby/bundle-install
